# Generated by Django 3.1.5 on 2022-08-02 13:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RamUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsbPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True)),
                ('display_price', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('processor', models.CharField(max_length=255)),
                ('front_camera', models.IntegerField()),
                ('back_camera', models.IntegerField()),
                ('has_earphone_jack', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('launch_date', models.DateField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='mobile_images')),
                ('spec', models.ImageField(blank=True, null=True, upload_to='mobile_specs')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='ecommerce.brand')),
                ('color', models.ManyToManyField(related_name='mobile', to='ecommerce.Color')),
                ('ram_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='ecommerce.ramunit')),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='ecommerce.screentype')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='mobile', to='ecommerce.Tag')),
                ('usb_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='ecommerce.usbport')),
            ],
        ),
    ]
