# Generated by Django 3.1.5 on 2022-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='spec',
            field=models.FileField(blank=True, null=True, upload_to='mobile_specs'),
        ),
    ]
