# Generated by Django 3.1.5 on 2022-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20220803_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileimage',
            name='image_storage',
        ),
        migrations.AddField(
            model_name='mobileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images'),
        ),
        migrations.DeleteModel(
            name='ImageStorage',
        ),
    ]
