# Generated by Django 3.1.5 on 2022-08-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20220804_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
