# Generated by Django 3.1.5 on 2022-08-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_mobile_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mobile_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='mobileimage',
            name='image',
        ),
        migrations.AddField(
            model_name='mobileimage',
            name='image_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_image', to='ecommerce.imagestorage'),
        ),
    ]
