# Generated by Django 3.1.5 on 2021-05-13 11:57

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=user.models.LowercaseEmailField(max_length=255, unique=True),
        ),
    ]
