# Generated by Django 3.1.5 on 2021-05-14 04:01

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('user', 'User')
    for row in MyModel.objects.all():
        row.unique_id = uuid.uuid4()
        row.save(update_fields=['unique_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_unique_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
